name: System tests

on:
  push:
  workflow_dispatch:


jobs:
  system-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: "Build docker image"
        run: make docker_build
      - name: "Run docker compose"
        run: "make deploy PORT=9292 FA_COOKIE=\"${{ secrets.TEST_COOKIE }}\""
      - name: "List docker containers"
        run: docker ps -a
