name: System tests

on:
  push:
  workflow_dispatch:


jobs:
  system-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: "Build docker image"
        run: make docker_build
      - name: "Run docker compose"
        run: "make deploy_bg PORT=9292 FA_COOKIE=\"${{ secrets.TEST_COOKIE }}\""
      - name: "Snooze a sec"
        run: sleep 60
      - name: "Check home page"
        run: curl http://localhost:9292
      - name: "Check home endpoint"
        run: curl http://localhost:9292/home.json
      - name: "List docker containers"
        run: docker ps -a
