name: System tests

on:
  push:
    branches-ignore:
      - "dependabot/**"
  pull_request:
    branches:
      - "master"
  workflow_dispatch:


jobs:
  system-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: "Build docker image"
        run: make docker_build
      - name: "Run docker compose"
        run: "make deploy_bg PORT=9292"
        env:
          FA_COOKIE: ${{ secrets.TEST_COOKIE_ESCAPED }}
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1.2
      - name: Install dependencies
        run: bundle install
      - name: "Run system tests"
        run: bundle exec "rspec spec tests/system_spec.rb"
        env:
          server_url: "http://localhost:9292"
          test_cookie: ${{ secrets.TEST_COOKIE}}
          test_cookie_user_2: ${{ secrets.COOKIE_FAFEED_2 }}
